{
 "title": "Abacus Metric pro Datenpool",
 "description": "Zeigt die Abacus Metrics für alle Abacus-Server in einem Bucket",
 "tags": [ "1.0.0" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Kunde", "query": { "query": "buckets()" } },
   {
    "name": "environment",
    "label": "Umgebung",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_total_bytes\")\r\n  |> group(columns: [\"environment\"])\r\n  |> distinct(column: \"environment\")\r\n  |> keep(columns: [\"_value\"])\r\n"
    }
   },
   { "name": "DS", "label": "Data source", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System - CPU Load",
   "type": "timeseries",
   "description": "All CPUs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_cpu_used\")\r\n  |> filter(fn: (r) => r.environment =~ /${environment:regex}/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"value\")"
    }
   ]
  },
  {
   "title": "System - Free Memory",
   "type": "timeseries",
   "description": "Total:  \nAmount of physical memory.\n\nUsed:  \nAmount of physical memory currently used.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_memory_available_bytes\")\r\n  |> filter(fn: (r) => r.environment =~ /${environment:regex}/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System - Free Disk Space ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_free_bytes\")\r\n  |> filter(fn: (r) => r.environment =~ /${environment:regex}/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System - Total Network Usage",
   "type": "timeseries",
   "description": "The rate at which bytes are sent and received over each network adapter, including framing characters. Network Interface\\Bytes Total/sec is a sum of Network Interface\\Bytes Received/sec and Network Interface\\Bytes Sent/sec.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windows_default_pdh_network_interface_bytes_total_sec\")\r\n  |> filter(fn: (r) => r.environment =~ /${environment:regex}/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Abacus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Abacus - Sessions (ULC + Web)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_ulc_session_active\" or r[\"_measurement\"] == \"abacus_vaadin_ui_active\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> group(columns: [\"instancename\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum_per_instance\")"
      }
     ]
    },
    {
     "title": "Abacus - Open Tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_tables_count\")\r\n  |> filter(fn: (r) => r[\"_value\"] != 0) \r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> group(columns: [\"instancename\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum_tables_per_instance\")"
      }
     ]
    },
    {
     "title": "JVM - CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_cpu_usage\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> group(columns: [\"instancename\"]) \r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum_process_cpu_usage\")"
      }
     ]
    },
    {
     "title": "JVM - Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used_bytes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\",\"instancename\"])\r\n  |> group(columns: [\"instancename\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false) \r\n  |> yield(name: \"sum\")"
      }
     ]
    },
    {
     "title": "JVM - Handles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_files_open_files\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\",\"instancename\"])\r\n  |> group(columns: [\"instancename\"])\r\n  |> aggregateWindow(every: 15s, fn: sum, createEmpty: false) \r\n  |> yield(name: \"sum\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Datenbank",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CTree - Table Operation Rate [1min]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_ctree_operations_total\")\r\n  |> filter(fn: (r) => r[\"_value\"] != 0) \r\n  |> derivative(unit: 1m, nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"_value\",\"instancename\"])\r\n  |> group(columns: [\"instancename\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"rate_abacus_ctree_operations_total\")"
      }
     ]
    },
    {
     "title": "CTree - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_ctree_sessions\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"instancename\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}