{
 "title": "Abacus Metric pro Instanz - Schnellübersicht",
 "description": "Zeigt die Abacus Metrics für einen einzelnen Abacus-Server.",
 "tags": [ "1.0.0" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "bucket", "label": "Kunde", "query": { "query": "buckets()" } },
   {
    "name": "instancename",
    "label": "Instanz",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_total_bytes\")\r\n  |> group(columns: [\"instancename\"])\r\n  |> distinct(column: \"instancename\")\r\n  |> keep(columns: [\"_value\"])\r\n"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used_bytes\")\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"job\"] != \"AbaMetricsService\" and r[\"job\"] != \"AbaMonitorService\" and r[\"job\"] != \"AbaAuditServer\")\r\n  |> group(columns: [\"job\"])\r\n  |> distinct(column: \"job\")\r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "aggregationInterval",
    "label": "aggregationInterval",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus\")\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n  |> keep(columns: [\"aggregationInterval\"])\r\n  |> map(fn: (r) => {\r\n      duration_ms = int(v: r.aggregationInterval)\r\n      window = if duration_ms % 60000 == 0 then\r\n          string(v: duration_ms / 60000) + \"m\"\r\n      else\r\n          string(v: duration_ms / 1000) + \"s\"\r\n      return { window_interval: window, _value: duration_ms }\r\n  })\r\n  |> keep(columns: [\"window_interval\"])\r\n  |> yield(name: \"window_interval\")"
    }
   },
   { "name": "DS", "label": "Data source", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System - CPU",
   "type": "timeseries",
   "description": "All CPUs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_cpu_used\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"value\")"
    }
   ]
  },
  {
   "title": "System CPU - Process Time Rate [1min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_process_kernel_time_total\" or r[\"_measurement\"] == \"system_info_process_user_time_total\")\r\n  |> filter(fn: (r) => r[\"_value\"] != 0) \r\n  |> derivative(unit: 1m, nonNegative: true)\r\n  |> group(columns: [\"name\", \"pid\"])\r\n  |> keep(columns: [\"_time\", \"_value\",\"name\", \"pid\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"rate_user_time\")"
    }
   ]
  },
  {
   "title": "System - Memory",
   "type": "timeseries",
   "description": "Total:  \nAmount of physical memory.\n\nUsed:  \nAmount of physical memory currently used.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_memory_total_bytes\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    { "expression": "$A - $B", "reducer": "min", "type": "math" }
   ]
  },
  {
   "title": "System - Swap Size",
   "type": "timeseries",
   "description": "Total:  \nThe current size of the paging/swap file(s). If the paging/swap file can be extended, this is a soft limit.\n\nUsed:  \nThe current memory committed to the paging/swap file(s).\n\nFor more information see:  \nhttps://en.wikipedia.org/wiki/Memory_paging#Implementations",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_swap_total_bytes\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_swap_used_bytes\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"used\")"
    }
   ]
  },
  {
   "title": "System - Page Swap Rate [1min]",
   "type": "timeseries",
   "description": "In:  \nNumber of pages read from paging/swap file(s) to resolve hard page faults. (Hard page faults occur when a process requires code or data that is not in its working set or elsewhere in physical memory, and must be retrieved from disk.) This property was designed as a primary indicator of the kinds of faults that cause system-wide delays. It includes pages retrieved to satisfy faults in the file system cache (usually requested by applications) and in non-cached mapped memory files.\n\nOut:  \nNumber of pages written to paging/swap file(s) to free up space in physical memory. Pages are written back to disk only if they are changed in physical memory, so they are likely to hold data, not code. A high rate of pages output might indicate a memory shortage. The operating system writes more pages back to disk to free up space when physical memory is in short supply.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_swap_pages_total\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"In\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 45s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"rate\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_info_swap_pages_total\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Out\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 45s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"rate\")"
    }
   ]
  },
  {
   "title": "System - Network (Bytes/Second)",
   "type": "timeseries",
   "description": "The rate at which bytes are sent and received over each network adapter, including framing characters. Network Interface\\Bytes Total/sec is a sum of Network Interface\\Bytes Received/sec and Network Interface\\Bytes Sent/sec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windows_default_pdh_network_interface_bytes_received_sec\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"item\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    { "expression": "-${sent_positive}", "type": "math" }
   ]
  },
  {
   "title": "System - Working Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_total_bytes\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  { "title": "Abacus Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU - Abacus JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_cpu_usage\")\r\n  |> keep(columns: [\"_time\", \"_value\",\"job\"])\r\n  |> group(columns: [\"job\"]) \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU - Garbage Collector",
   "type": "timeseries",
   "description": "An approximation of the percent of CPU time used by GC activities over the last lookback period or since monitoring began, whichever is shorter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_overhead_percent\")\r\n  |> group(columns: [\"job\", \"_field\", \"action\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "$service - Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.instancename == \"${instancename}\" and\r\n    r.job == \"${service}\" and\r\n    r.area == \"heap\" and\r\n    (\r\n      r._measurement == \"jvm_memory_max_bytes\" or\r\n      r._measurement == \"jvm_memory_committed_bytes\" or\r\n      r._measurement == \"jvm_memory_used_bytes\"\r\n    ) and\r\n    (\r\n      r.id == \"G1 Eden Space\" or\r\n      r.id == \"G1 Old Gen\" or\r\n      r.id == \"G1 Survivor Space\"\r\n    )\r\n  )\r\n  |> aggregateWindow(every: ${aggregationInterval}, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\", \"_measurement\"], columnKey: [\"id\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) =>\r\n  exists r[\"G1 Eden Space\"] and exists r[\"G1 Old Gen\"] and exists r[\"G1 Survivor Space\"]\r\n)\r\n|> map(fn: (r) => ({\r\n  _time: r._time,\r\n  _measurement: r._measurement,\r\n  _value: r[\"G1 Eden Space\"] + r[\"G1 Old Gen\"] + r[\"G1 Survivor Space\"]\r\n}))\r\n|> aggregateWindow(every: ${aggregationInterval}, fn: mean, createEmpty: false)\r\n|> yield(name: \"heap_totals_smoothed\")"
    }
   ]
  },
  {
   "title": "Abacus - Open Tables, Handel, Sessions und CTree.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Abacus - Open Tables",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_tables_count\")\r\n  |> filter(fn: (r) => r[\"_value\"] != 0) \r\n  |> keep(columns: [\"_time\", \"_value\", \"job\", \"type\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Handles",
     "type": "timeseries",
     "description": "The open handles count (eg: file handles).\n\nOn Windows platform this is GetProcessHandleCount (https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocesshandlecount).\n\nOn Non-Windows this is determined via /proc/self/fd.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_files_open_files\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"job\", \"type\"])\r\n  |> aggregateWindow(every: 15s, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum_of_jvm_memory_used_bytes\")"
      }
     ]
    },
    {
     "title": "Abacus - Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_ulc_session_active\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"job\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_vaadin_ui_active\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"job\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"used\")"
      }
     ]
    },
    {
     "title": "CTree - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_ctree_sessions\" or r[\"_measurement\"] == \"abacus_ctree_sessions_max\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CTree - Table Operation Rate [1min]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"instancename\"] == \"${instancename}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abacus_ctree_operations_total\")\r\n  |> filter(fn: (r) => r[\"_value\"] != 0) \r\n  |> derivative(unit: 1m, nonNegative: true)\r\n  |> group(columns: [\"op\"])\r\n  |> keep(columns: [\"_time\", \"_value\",\"op\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"rate_abacus_ctree_operations_total\")"
      }
     ]
    }
   ]
  }
 ]
}